### ISSUE TITLE
2d[TASK] 组块一：是什么？

### ISSUE THREAD

**Issue by tanchangde** [tanchangde/ModelParentToolkit#5]
- `2d` 表示本任务的交付时间为自 Issue 打开后 2 天内
- `TASK` 表示本 Issue 为一个任务，请重点关注**任务安排、交付说明**

## 目录

- [说明](#说明)
- [任务清单](#任务清单)
- [交付说明](#交付说明)
- [已读反馈](#已读反馈)
- [ChangeLog](#changelog)

## 任务清单

～此处填充你所负责输出结果清单，如：

- [ ] 下载知网中小学生手游相关文献
- [ ] 识别关键变量
- [ ] 通过公开报道、报告，形成中小学生玩手游时空认识。如在线时间、空间。
  - [x] 到底有多少中学生在玩手游？

...

## 交付说明

- 以 Comment 形式在本 Issue 提交结论卡片
- 一个 Comment 讲清楚一个信息点
- 卡片稍作调整便可直接嵌入项目最终路演文稿

## 参考资料

- 感受 [项目路演最终呈现 Keynote 「安身与立命——职业生涯自救指南」](https://github.com/linhaotao/AIhackers001BP-NationalstaffsCareerRPT/issues/5)
- 感受 [项目路演最呈现 演讲逐字稿 「安身与立命——职业生涯自救指南」](https://github.com/linhaotao/AIhackers001BP-NationalstaffsCareerRPT/issues/5)

## ChangeLog

- 20181104 长德 @tanchangde init

**Comment by tanchangde** [comment]
## 到底有多少中小学生在玩王者？

一百万 OR 二千万

### 按照直接的第三方数据求解

`54128000 * 2.7% = 1461456`

`1461456 ／ (44420600 + 100937000) = 1%`

每天登陆，146 万人，占比在校中小学生 1% 。也即每 100 个中小学生有一个“王者”每天活跃。

### 按照间接的第三方数据求解

`(44420600 + 100937000) * 68.1% * 21.78% = 21480510`

`21480510  /  (44420600 + 100937000)  = 14.78%`

接触王者荣耀的中小学生，2148 万人，占比在校中小学生 14.78%。即每 100 个中小学生有 14 个中小学生手机中安装有王者荣耀。

### 数据说明

- 2.7%，2016 年 3 月-2017 年 4 月，王者荣耀用户中中小学生占比
- 54128000，2017 年 5 月，王者荣耀日活跃用户规模
- 44420600，2017 年中学在校生
- 100937000，2017 年小学在校生
- 68.1% ，《中美日韩网络时代亲子关系的对比研究报告》，中国中小学生智能手机拥有率
- 21.78% ，截至2017年12月最后一周王者荣耀在手机中的安装率

### 参考资料

- 2017年全国教育事业发展统计公报 - 中华人民共和国教育部政府门户网站. (n.d.). Retrieved November 7, 2018, from http://www.moe.gov.cn/jyb_sjzl/sjzl_fztjgb/201807/t20180719_343508.html
- TalkingData-王者荣耀热点报告. (n.d.). Retrieved November 7, 2018, from http://mi.talkingdata.com/report-detail.html?id=529
- 极光大数据：2017年手机游戏市场研究报告 | GameLook.com.cn. (n.d.). Retrieved November 7, 2018, from http://www.gamelook.com.cn/2018/02/320342
- 中国中小学生智能手机拥有率近七成 超过美日-中青在线. (n.d.). Retrieved November 15, 2018, from http://zqb.cyol.com/html/2018-10/30/nw.D110000zgqnb_20181030_5-07.htm

## ChangeLog

- 181110 增补月活
- 181116 交叉验证

**Comment by tanchangde** [comment]
## 王者荣耀用户群活跃时段分布

中小学生中午以及晚间时段较为活跃

![timeStyle](https://ws2.sinaimg.cn/large/006tNbRwgy1fx2akbd6koj31kw0l9agv.jpg)

### 参考资料

- TalkingData-王者荣耀热点报告. (n.d.). Retrieved November 7, 2018, from http://mi.talkingdata.com/report-detail.html?id=529

**Comment by tanchangde** [comment]
## 王者荣耀中小学生全国分布图

从区域分布看，活跃的王者荣耀中小学生基 本分布在全国各地，且主要集聚于“黑河 腾冲线”以东地区，例如北京、上海、广 州、深圳、成都、福州、济南、沈阳、西 安、南昌等地。

![heatMap](https://ws3.sinaimg.cn/large/006tNbRwgy1fx2ahp9l7xj31kw0xekjm.jpg)

### 参考资料

- TalkingData-王者荣耀热点报告. (n.d.). Retrieved November 7, 2018, from http://mi.talkingdata.com/report-detail.html?id=529

**Comment by tanchangde** [comment]
## 手游是什么？

手机游戏（简称手游，英语：Mobile Game）是在功能手机、智能手机 / 平板电脑、智能手表、 PDA、便携式媒体播放器或图形计算器上进行的游戏。

![mobileGame](https://ws3.sinaimg.cn/large/006tNbRwgy1fx2asw3ir7j30go0b40tb.jpg)

### 参考资料

- Mobile game - Wikipedia. (n.d.). Retrieved November 9, 2018, from https://en.wikipedia.org/wiki/Mobile_game

**Comment by tanchangde** [comment]
## 当今手游有多普遍性？

### 从营收上看，手游占中国网络游戏 6 成

![](https://ws2.sinaimg.cn/large/006tNbRwgy1fx2b5rnckoj31kw0ns4qp.jpg)

### 从用户规模上看，手游用户占中国人口 4 成 

![](https://ws2.sinaimg.cn/large/006tNbRwgy1fx2bc1dje6j31kw0mv7jr.jpg)

### 参考资料

- 2018年中国移动游戏行业研究报告. (n.d.). Retrieved November 9, 2018, from http://report.iresearch.cn/wx/report.aspx?id=3266

**Comment by tanchangde** [comment]
## 手游对中小学生的影响

### 身体层面消极影响

改变大脑静息态默认网络
导致大脑奖惩系统异常
冲动控制功能异常

### 行为层面

#### 积极影响

- 提高沟通与社会交往能力
- 开发智力，提高日常反应能力
- 培养全局意识及目标导向的行为能力

#### 消极影响

- 荒废学业，影响身体健康
- 家庭关系受到挑战
- 生过度消费行为

### 心理层面

#### 积极影响

- 增强团队合作精神
- 把握角色定位，增强自我意识
- 提高情绪管理能力

#### 消极影响

- 消解传统文化的意义
- 产生依赖心理，引发网瘾
- 扭曲三观，导致心理问题
- 网络欺凌的 


## 参考资料

- 方晓彤. (2018). 社交类手游对青少年的影响及其社会工作介入研究 (硕士). 南京大学.
- 丁伟娜. (2014). 运用功能磁共振技术探讨网络游戏成瘾青少年特定脑功能的改变 (硕士). 上海交通大学. 

## ChangeLog

- 181116 增补身体层面影响

**Comment by Freshniu** [comment]
## 网络成瘾临床诊断标准

北京军区总医院成瘾科主任陶然的《网络成瘾临 床诊断标准》纳入正式出版的《DSM一5诊断与统计手 册》。这标志着中国网络游戏成瘾标准首次被国际采 纳。世界卫生组织对疾病概念的界定主要遵循以下两条标准:一是社会功能(包括人际关系、工作学习、 日常生活)受损;二是给自己和他人带来痛苦。“如果以这两条标准来衡量，网瘾就是一种病。”陶然。

新的网瘾诊断标准包括9条:

该诊断标准共有9条：
1、渴求症状(对网络使用有强烈的渴求或冲动感)；
2、戒断症状(易怒、焦虑和悲伤等)；
3、耐受性(为达到满足感而不断 增加使用网络的时间和投入的程度)；
4、难以停止上网；
5、因游戏而减少了其他兴趣；
6、即使知道后果仍过度游戏；
7、向他人撒谎玩游戏的时间和费 用；
8、用游戏来回避现实或缓解负性情绪；
9、玩游戏危害到或失去了友谊、工作

 陶然提醒，当发现孩子只要符合5条或5条以上标准的就可以判定孩子已经产生网瘾，需要及时到正规 医疗机构治疗;而在2~5条之间的则属于网瘾高危人群，说明已经对网络产生过度的依赖。给日常学习和 生活带来了影响，此时更需要家长和孩子引起高度的重视，及时预防网瘾 。

[DSM-5正式出版：网瘾被认定为精神病新病种_华人心理健康报-_新浪博客](http://blog.sina.com.cn/s/blog_5168ec1b0101lgx8.html)
[如何戒掉《王者荣耀》的瘾](http://kns.cnki.net/kns/detail/detail.aspx?QueryID=14&CurRec=166&recid=&FileName=KJJT201709041&DbName=CJFDLASN2017&DbCode=CJFQ&yx=&pr=CJFT2017;CJFU2017;&URLID=)
